# Generated by Django 5.2.6 on 2026-01-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_profile_delete_mijoz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='telefon',
        ),
    ]
